# File upload configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=./uploads

# application.properties
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=INFO

# JWT Configuration
app.jwtSecret=8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb
app.jwtExpirationInMs=86400000

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update 