spring:
  datasource:
    url: jdbc:postgresql://10.88.190.5:8082/weldtelecom
    username: postgres
    password: 1900AscotPkwy
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    org.alloy: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO