package org.alloy.repositories;

import org.alloy.models.ReportHistory;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ReportHistoryRepository extends JpaRepository<ReportHistory, Long> {
    
    /**
     * Найти отчеты по типу, отсортированные по дате генерации (новые сначала)
     */
    List<ReportHistory> findByReportTypeOrderByGeneratedAtDesc(String reportType);
    
    /**
     * Найти все отчеты, отсортированные по дате генерации (новые сначала)
     */
    @Query("SELECT r FROM ReportHistory r ORDER BY r.generatedAt DESC")
    List<ReportHistory> findAllByOrderByGeneratedAtDesc();
    
    /**
     * Найти отчеты по пользователю, отсортированные по дате генерации (новые сначала)
     */
    List<ReportHistory> findByGeneratedByOrderByGeneratedAtDesc(String generatedBy);
    
    /**
     * Найти автоматически сгенерированные отчеты
     */
    List<ReportHistory> findByIsAutoGeneratedTrueOrderByGeneratedAtDesc();
    
    /**
     * Найти отчеты по ID автоматического отчета
     */
    List<ReportHistory> findByAutomatedReportIdOrderByGeneratedAtDesc(Long automatedReportId);
}
