package org.alloy.models;

import javax.persistence.*;
import java.time.LocalDateTime;

/**
 * Модель для хранения истории сгенерированных отчетов
 */
@Entity
@Table(name = "report_history")
public class ReportHistory {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @Column(name = "report_type", nullable = false)
    private String reportType;        // Тип отчета (equipment, welders, materials, etc.)
    
    @Column(name = "report_name", nullable = false)
    private String reportName;        // Название отчета на русском
    
    @Column(name = "format", nullable = false)
    private String format;            // Формат отчета (PDF, EXCEL, CSV)
    
    @Column(name = "period")
    private String period;            // Период отчета
    
    @Column(name = "date_generated", nullable = false)
    private LocalDateTime generatedAt; // Время генерации
    
    @Column(name = "file_name")
    private String fileName;          // Имя файла для скачивания
    
    @Column(name = "file_size")
    private Long fileSize;            // Размер файла в байтах
    
    @Column(name = "generated_by")
    private String generatedBy;       // Кто сгенерировал (пока можно оставить "Система")
    
    @Column(name = "is_auto_generated")
    private Boolean isAutoGenerated = false;  // Автоматически сгенерированный отчет
    
    @Column(name = "automated_report_id")
    private Long automatedReportId;   // ID автоматического отчета, который сгенерировал этот отчет

    public ReportHistory() {}

    public ReportHistory(String reportType, String reportName, String format, String period, 
                        String fileName, Long fileSize, String generatedBy) {
        this.reportType = reportType;
        this.reportName = reportName;
        this.format = format;
        this.period = period;
        this.generatedAt = LocalDateTime.now();
        this.fileName = fileName;
        this.fileSize = fileSize;
        this.generatedBy = generatedBy;
        this.isAutoGenerated = false;
    }

    public ReportHistory(String reportType, String reportName, String format, String period, 
                        String fileName, Long fileSize, String generatedBy, Long automatedReportId) {
        this.reportType = reportType;
        this.reportName = reportName;
        this.format = format;
        this.period = period;
        this.generatedAt = LocalDateTime.now();
        this.fileName = fileName;
        this.fileSize = fileSize;
        this.generatedBy = generatedBy;
        this.isAutoGenerated = true;
        this.automatedReportId = automatedReportId;
    }

    // Геттеры и сеттеры
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getReportType() { return reportType; }
    public void setReportType(String reportType) { this.reportType = reportType; }

    public String getReportName() { return reportName; }
    public void setReportName(String reportName) { this.reportName = reportName; }

    public String getFormat() { return format; }
    public void setFormat(String format) { this.format = format; }

    public String getPeriod() { return period; }
    public void setPeriod(String period) { this.period = period; }

    public LocalDateTime getGeneratedAt() { return generatedAt; }
    public void setGeneratedAt(LocalDateTime generatedAt) { this.generatedAt = generatedAt; }

    public String getFileName() { return fileName; }
    public void setFileName(String fileName) { this.fileName = fileName; }

    public Long getFileSize() { return fileSize; }
    public void setFileSize(Long fileSize) { this.fileSize = fileSize; }

    public String getGeneratedBy() { return generatedBy; }
    public void setGeneratedBy(String generatedBy) { this.generatedBy = generatedBy; }

    public Boolean getIsAutoGenerated() { return isAutoGenerated; }
    public void setIsAutoGenerated(Boolean isAutoGenerated) { this.isAutoGenerated = isAutoGenerated; }

    public Long getAutomatedReportId() { return automatedReportId; }
    public void setAutomatedReportId(Long automatedReportId) { this.automatedReportId = automatedReportId; }

    /**
     * Получить размер файла в читаемом формате
     */
    public String getFormattedFileSize() {
        if (fileSize < 1024) {
            return fileSize + " Б";
        } else if (fileSize < 1024 * 1024) {
            return String.format("%.1f КБ", fileSize / 1024.0);
        } else {
            return String.format("%.1f МБ", fileSize / (1024.0 * 1024.0));
        }
    }

    /**
     * Получить расширение файла
     */
    public String getFileExtension() {
        if (fileName != null && fileName.contains(".")) {
            return fileName.substring(fileName.lastIndexOf(".") + 1).toUpperCase();
        }
        return format;
    }
}
